### ISSUE TITLE
about the bluetooth protocol on iblazr

### ISSUE THREAD

**Issue by xiongyoudou** [ConcepterDev/iblazr-sdk-ios#1]
HI,thanks for your sharing!
i have some cofused on the iblazr device.
as apple article said [iOS:Supported Bluetooth profiles](https://support.apple.com/en-us/HT204387)  contain:"HFP PBAP A2DP AVRCP  PAN HID MAP"
![tmp7c2f6e05](https://cloud.githubusercontent.com/assets/2812119/18115110/2476bc14-6f6f-11e6-952b-46f31888c727.png)
so ,what's the bluetooth profiles used on your device?

**Comment by andrew-skrypnyk** [comment]
Hello Xiongyoudou, please accept my apologies for the late response. 
Our iblazr 2 used our own protocol, see more here: https://github.com/ConcepterDev/iblazr-2-protocol. (based on HID)
